version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  web:
    restart: always
    build:
      context: .
    environment:
      - OTREE_PRODUCTION=1
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    command: bash -c 'OTREE_ADMIN_PASSWORD="123456" OTREE_AUTH_LEVEL="STUDY" nohup  otree runprodserver --port=8001 &'
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
  redisdata: